"""Generate web/constants.js from config.ENV (single source of truth).

Run: python scripts/export_constants.py
The web demo reads ONLY from `C` — no magic numbers in JS (see INTERFACES.md).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import config  # noqa: E402


def main():
    c = dict(config.ENV)
    c["FPS"] = 30
    c["N_ACTIONS"] = config.N_ACTIONS
    out = config.REPO_ROOT / "web" / "constants.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// GENERATED by scripts/export_constants.py — do not edit by hand.\n"
        "const C = " + json.dumps(c, indent=2) + ";\n"
    )
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
