// GENERATED by scripts/export_constants.py — do not edit by hand.
const C = {
  "W": 64,
  "H": 64,
  "paddle_h": 12,
  "paddle_w": 2,
  "left_x": 2,
  "right_x": 60,
  "agent_speed": 2.0,
  "opp_speed": 1.0,
  "opp_deadzone": 1.0,
  "ball_size": 2,
  "ball_vx": 1.5,
  "max_vy": 1.25,
  "serve_vy_choices": [
    -1.0,
    -0.5,
    0.0,
    0.5,
    1.0
  ],
  "max_steps": 500,
  "r_score": 1.0,
  "r_concede": -1.0,
  "r_hit": 0.1,
  "FPS": 30,
  "N_ACTIONS": 3
};
