/* pong.js — browser Pong: human (LEFT paddle) vs. an ONNX policy (RIGHT paddle).
 *
 * The simulation is an EXACT JS port of the Python env physics contract
 * (INTERFACES.md, "Env API"): float positions, Math.floor(x + 0.5) rounding,
 * and the verbatim step order:
 *   1 paddles move -> 2 ball moves -> 3 wall bounce -> 4 paddle collision
 *   (crossing test vs PREV x) -> 5 scoring -> 6 truncation -> 7 render.
 *
 * All env constants come from the global `C` (web/constants.js, generated by
 * scripts/export_constants.py). No magic env numbers below — only structural
 * facts fixed by the contract itself (walls are the single rows 0 and H-1,
 * ONNX input stack depth 4) and pure display choices (8x upscale).
 */
"use strict";
(() => {

// ------------------------------------------------------------------ DOM ----
const $ = (id) => document.getElementById(id);
const bannerEl = $("banner");

function showBanner(msg, kind) { bannerEl.textContent = msg; bannerEl.className = kind; }
function clearBanner()         { bannerEl.textContent = "";  bannerEl.className = ""; }

// constants.js guard: halt hard if the generated constants are missing.
if (typeof C === "undefined") {
  showBanner("constants.js missing — run scripts/export_constants.py", "error");
  throw new Error("constants.js missing — run scripts/export_constants.py");
}

// ------------------------------------------------------ derived constants ----
const W = C.W, H = C.H;
const BS = C.ball_size, PH = C.paddle_h, PW = C.paddle_w;
const WALL_TOP    = 1;              // first row inside the top wall (row 0 is wall)
const BALL_MAX_Y  = H - 1 - BS;     // last ball top-left y inside the bottom wall
const PADDLE_MIN_Y = WALL_TOP;
const PADDLE_MAX_Y = H - 1 - PH;    // clamp range [1, 51] for the defaults
const LEFT_PLANE  = C.left_x + PW;  // right face of the left paddle  (x = 4)
const RIGHT_PLANE = C.right_x;      // left face of the right paddle  (x = 60)
const NF = C.FRAME_STACK ?? 4;      // ONNX contract fixes input [1, 4, 64, 64]
const SCALE = 8;                    // display upscale only — never touches physics
const DT_MS = 1000 / C.FPS;
const MAX_BACKLOG_MS = 5 * DT_MS;   // accumulator clamp: never "catch up" > 5 steps

// contract rounding: identical to Python int(floor(x + 0.5))
const px = (v) => Math.floor(v + 0.5);
const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v));

// ------------------------------------------------------------- game state ----
const S = {
  bx: 0, by: 0,   // ball top-left (floats)
  vx: 0, vy: 0,
  ly: 0, ry: 0,   // paddle top-left y (floats); left = human, right = agent
  t: 0,           // steps since serve (truncation counter)
  scoreHuman: 0, scoreAgent: 0,
};

function serve() {
  S.bx = (W - BS) / 2;              // 31 for defaults
  S.by = (H - BS) / 2;              // 31
  S.ly = (H - PH) / 2;              // 26
  S.ry = (H - PH) / 2;              // 26
  // Runtime RNG parity with seeded numpy is NOT required (see DECISIONS):
  // the demo needs identical *dynamics*, not identical serve sequences.
  S.vx = (Math.random() < 0.5 ? 1 : -1) * C.ball_vx;
  S.vy = C.serve_vy_choices[Math.floor(Math.random() * C.serve_vy_choices.length)];
  S.t = 0;
}

// ----------------------------------------------------------------- physics ----
function movePaddle(y, action, speed) {          // 0 stay, 1 up (y-), 2 down (y+)
  if (action === 1) y -= speed;
  else if (action === 2) y += speed;
  return clamp(y, PADDLE_MIN_Y, PADDLE_MAX_Y);
}

// scripted tracker (the contract's opponent policy) — fallback right paddle
function trackerAction(paddleY) {
  const paddleCy = paddleY + PH / 2;
  const ballCy = S.by + BS / 2;
  if (paddleCy < ballCy - C.opp_deadzone) return 2;   // down
  if (paddleCy > ballCy + C.opp_deadzone) return 1;   // up
  return 0;
}

function verticalOverlap(paddleY) {              // contract: by+BS > py && by < py+PH
  return S.by + BS > paddleY && S.by < paddleY + PH;
}

function deflectVy(paddleY) {
  const offset = (S.by + BS / 2) - (paddleY + PH / 2);
  return clamp(offset / (PH / 2), -1, 1) * C.max_vy;
}

// One env step. Returns true if the point/truncation reset happened (the state
// after return is then the FIRST frame of the new rally — auto-reset semantics).
function step(humanAct, agentAct, agentSpeed) {
  // 1. paddles move (agent at its NEW y before collision tests, per contract)
  S.ly = movePaddle(S.ly, humanAct, C.agent_speed);
  S.ry = movePaddle(S.ry, agentAct, agentSpeed);

  // 2. ball moves (store prev x BEFORE the move for the crossing tests)
  const prevBx = S.bx;
  S.bx += S.vx;
  S.by += S.vy;

  // 3. wall bounce: reflect ball top-left y at WALL_TOP / BALL_MAX_Y, flip vy
  if (S.by < WALL_TOP) {
    S.by = 2 * WALL_TOP - S.by;          // y = 2 - y
    S.vy = -S.vy;
  } else if (S.by > BALL_MAX_Y) {
    S.by = 2 * BALL_MAX_Y - S.by;        // y = 122 - y
    S.vy = -S.vy;
  }

  // 4. paddle collision — crossing test vs PREV x, paddles at their NEW y
  if (S.vx > 0) {
    // right paddle: ball RIGHT edge vs plane x = RIGHT_PLANE, prev <= plane < new
    const prevR = prevBx + BS, newR = S.bx + BS;
    if (prevR <= RIGHT_PLANE && RIGHT_PLANE < newR && verticalOverlap(S.ry)) {
      S.bx = 2 * RIGHT_PLANE - newR - BS;      // reflect right edge about plane
      S.vx = -S.vx;
      S.vy = deflectVy(S.ry);
    }
  } else if (S.vx < 0) {
    // left paddle: ball LEFT edge vs plane x = LEFT_PLANE (mirrored test)
    if (S.bx < LEFT_PLANE && LEFT_PLANE <= prevBx && verticalOverlap(S.ly)) {
      S.bx = 2 * LEFT_PLANE - S.bx;            // reflect left edge about plane
      S.vx = -S.vx;
      S.vy = deflectVy(S.ly);
    }
  }

  // 5. scoring: ball fully off-screen
  let point = 0;                                // agent perspective, like the env
  if (S.bx > W - 1) point = -1;                 // off right => LEFT (human) scores
  else if (S.bx + BS < 0) point = +1;           // off left  => RIGHT (agent) scores

  // 6. truncation
  S.t += 1;
  let reset = false;
  if (point !== 0) {
    if (point > 0) S.scoreAgent += 1; else S.scoreHuman += 1;
    reset = true;
  } else if (S.t >= C.max_steps) {
    reset = true;                               // endless match: re-serve, no score
  }
  if (reset) serve();
  return reset;                                 // 7. render happens in the caller
}

// ---------------------------------------------------------------- renderer ----
// Identical to the Python renderer: Uint8Array(W*H), values {0, 255}, walls on
// rows 0 and H-1, score NEVER drawn into the frame (DOM scoreboard instead).
const frame = new Uint8Array(W * H);

function drawRect(f, x0, y0, w, h) {            // clipped to the frame
  const xa = Math.max(0, x0), xb = Math.min(W, x0 + w);
  const ya = Math.max(0, y0), yb = Math.min(H, y0 + h);
  for (let y = ya; y < yb; y++)
    for (let x = xa; x < xb; x++)
      f[y * W + x] = 255;
}

function renderFrame(f) {
  f.fill(0);
  for (let x = 0; x < W; x++) {                 // walls
    f[x] = 255;
    f[(H - 1) * W + x] = 255;
  }
  drawRect(f, C.left_x,  px(S.ly), PW, PH);
  drawRect(f, C.right_x, px(S.ry), PW, PH);
  drawRect(f, px(S.bx),  px(S.by), BS, BS);
}

// -------------------------------------------------------------- frame stack ----
let history = [];                               // NF frames, oldest -> newest

function refillHistory() {                      // match start / after each serve:
  const copy = frame.slice();                   // repeat the first frame NF times
  history = new Array(NF).fill(copy);
}

function pushHistory() {
  history.push(frame.slice());
  if (history.length > NF) history.shift();
}

const stackData = new Float32Array(NF * H * W); // reused every tick

function buildTensor() {
  for (let i = 0; i < NF; i++) {                // oldest -> newest, /255 into [0,1]
    const f = history[i], off = i * H * W;
    for (let j = 0; j < H * W; j++) stackData[off + j] = f[j] / 255;
  }
  return new ort.Tensor("float32", stackData, [1, NF, H, W]);
}

// --------------------------------------------------------------------- ONNX ----
const MODELS = { baseline: "model_baseline.onnx", dream: "model_dream.onnx" };
let session = null;
let modelName = null;

function enterFallback() {
  session = null;
  showBanner("model not loaded — scripted fallback", "warn");
  $("status-model").textContent = "scripted fallback";
  $("status-latency").textContent = "";
}

async function loadModel(key) {
  session = null;                               // fallback drives while loading
  modelName = key;
  clearBanner();
  $("status-model").textContent = "loading " + key + "…";
  if (typeof ort === "undefined") {             // CDN script failed to load
    enterFallback();
    return;
  }
  try {
    ort.env.wasm.numThreads = 1;                // plain http.server: no COOP/COEP
    const s = await ort.InferenceSession.create(MODELS[key]);
    if (modelName !== key) return;              // stale load (dropdown changed)
    session = s;
    latencies.length = 0;
    clearBanner();
    $("status-model").textContent = "model: " + key;
  } catch (e) {
    console.warn("ONNX load failed for", MODELS[key], e);
    if (modelName === key) enterFallback();
  }
}

// latency: rolling mean over the last 120 inferences
const latencies = [];
let latencyTick = 0;

function pushLatency(ms) {
  latencies.push(ms);
  if (latencies.length > 120) latencies.shift();
  if (++latencyTick % 10 === 0) {
    const mean = latencies.reduce((a, b) => a + b, 0) / latencies.length;
    $("status-latency").textContent = "inference: " + mean.toFixed(2) + " ms";
  }
}

// argmax(logits) -> {act, speed}; scripted tracker if no session
async function agentAction() {
  if (!session) return { act: trackerAction(S.ry), speed: C.opp_speed };
  try {
    const t0 = performance.now();
    const feeds = {};
    feeds[session.inputNames?.[0] ?? "frames"] = buildTensor();
    const out = await session.run(feeds);
    pushLatency(performance.now() - t0);
    const logits = (out.logits ?? out[session.outputNames?.[0]]).data;
    let best = 0;
    for (let i = 1; i < logits.length; i++) if (logits[i] > logits[best]) best = i;
    return { act: best, speed: C.agent_speed };
  } catch (e) {
    console.warn("ONNX inference failed:", e);
    enterFallback();
    return { act: trackerAction(S.ry), speed: C.opp_speed };
  }
}

// -------------------------------------------------------------------- input ----
const keys = { up: false, down: false };

function bindKeys() {
  const set = (e, down) => {
    if (e.key === "w" || e.key === "W" || e.key === "ArrowUp") {
      keys.up = down;
      if (e.key === "ArrowUp") e.preventDefault();
    } else if (e.key === "s" || e.key === "S" || e.key === "ArrowDown") {
      keys.down = down;
      if (e.key === "ArrowDown") e.preventDefault();
    }
  };
  window.addEventListener("keydown", (e) => set(e, true));
  window.addEventListener("keyup", (e) => set(e, false));

  const bindHold = (id, prop) => {
    const el = $(id);
    if (!el) return;
    el.addEventListener("pointerdown", (e) => { e.preventDefault(); keys[prop] = true; });
    for (const ev of ["pointerup", "pointercancel", "pointerleave"])
      el.addEventListener(ev, () => { keys[prop] = false; });
  };
  bindHold("btn-up", "up");
  bindHold("btn-down", "down");
}

function humanAction() {
  if (keys.up === keys.down) return 0;          // neither, or both held => stay
  return keys.up ? 1 : 2;
}

// ------------------------------------------------------------------ display ----
const canvas = $("screen");
canvas.width = W * SCALE;
canvas.height = H * SCALE;
const ctx = canvas.getContext("2d");
const off = document.createElement("canvas");
off.width = W;
off.height = H;
const octx = off.getContext("2d");
const img = octx.createImageData(W, H);

function blit() {
  const d = img.data;
  for (let i = 0; i < W * H; i++) {
    const v = frame[i];
    const j = i * 4;
    d[j] = v; d[j + 1] = v; d[j + 2] = v; d[j + 3] = 255;
  }
  octx.putImageData(img, 0, 0);
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(off, 0, 0, canvas.width, canvas.height);
}

function updateScoreDom() {
  $("score-human").textContent = S.scoreHuman;
  $("score-agent").textContent = S.scoreAgent;
}

// ---------------------------------------------------------------- game loop ----
// Fixed timestep C.FPS via accumulator on requestAnimationFrame. Inference is
// awaited inside the (re-entrancy-guarded) pump so the agent always acts on the
// CURRENT frame stack, exactly like training; the accumulator is clamped so a
// slow model can never trigger a catch-up spiral.
let acc = 0;
let last = performance.now();
let pumping = false;

async function pump() {
  if (pumping) return;
  pumping = true;
  try {
    while (acc >= DT_MS) {
      acc -= DT_MS;
      const hAct = humanAction();
      const { act, speed } = await agentAction();
      const reset = step(hAct, act, speed);
      renderFrame(frame);
      if (reset) {
        refillHistory();                        // new rally: first frame repeated
        updateScoreDom();
      } else {
        pushHistory();
      }
    }
  } finally {
    pumping = false;
  }
}

function raf(now) {
  acc = Math.min(acc + (now - last), MAX_BACKLOG_MS);
  last = now;
  pump();                                       // async; guarded against overlap
  blit();
  requestAnimationFrame(raf);
}

// --------------------------------------------------------------------- init ----
function init() {
  bindKeys();
  $("model-select").addEventListener("change", (e) => loadModel(e.target.value));

  serve();
  renderFrame(frame);
  refillHistory();                              // match start: first frame x NF
  updateScoreDom();
  blit();

  loadModel($("model-select").value);           // baseline by default
  last = performance.now();
  requestAnimationFrame(raf);
}

init();

})();
